# Generated by Django 3.1.5 on 2021-04-12 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eis', '0006_auto_20210303_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_achievement',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_confrence_organised',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_consultancy_projects',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_event_organized',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_expert_lectures',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_keynote_address',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_mtechphd_thesis',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_patents',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_published_books',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_research_papers',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_research_projects',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_session_chair',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_techtransfer',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='emp_visits',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='faculty_about',
            name='id',
        ),
        migrations.AddField(
            model_name='emp_achievement',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_confrence_organised',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_consultancy_projects',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_event_organized',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_expert_lectures',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_keynote_address',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_mtechphd_thesis',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_patents',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_published_books',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_research_papers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_research_projects',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_session_chair',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_techtransfer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_visits',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faculty_about',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
